name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Si tu archivo HTML está en una carpeta como /docs, configura la ruta de esa carpeta.
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          # Si el archivo está en una carpeta, actualiza la ruta
          path: ./docs   # Cambia esto si tu archivo HTML está en otra carpeta.
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Esta línea asegura que todo el repositorio se sube. Si es solo un archivo, usa './docs'.

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
